# Generated by Django 4.2.7 on 2023-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(blank=True, default=26, null=True, to='pizzas.pizzasize'),
        ),
    ]
