# Generated by Django 4.2.7 on 2023-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizzasize_pizza_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=4.55)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(blank=True, default=26, to='pizzas.pizzasize'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='prices',
            field=models.ManyToManyField(blank=True, default=5, to='pizzas.pizzaprice'),
        ),
    ]
