# Generated by Django 4.2.7 on 2023-11-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_alter_pizzaprice_options_alter_pizzasize_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzasize',
            options={'ordering': ['size']},
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='type',
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='name',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='pizzas',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(default=[0], max_length=60),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.categorie'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='prices',
            field=models.ManyToManyField(blank=True, default=[0], to='pizzas.pizzaprice'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(blank=True, default=[0], to='pizzas.pizzasize'),
        ),
        migrations.AlterField(
            model_name='pizzaprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
