# Generated by Django 4.2.7 on 2023-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_alter_pizzasize_options_remove_pizzaorder_pizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
