# Generated by Django 4.2.7 on 2023-11-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_alter_pizzaorder_pizzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='order_type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
